zuul:
  routes:
    ui:
      url: http://localhost:8081
    app1:
      url: http://localhost:8082
    resource:
      url: http://localhost:9000
security.user.password: password
management.context-path: /manage